CREATE TABLE MD_FILE_STORAGE
(
    ID                 BIGINT,
    BUSINESS_TYPE      VARCHAR(64) DEFAULT 'TEMP' NOT NULL,
    BUSINESS_ID        VARCHAR(64),
    STORAGE_PROVIDER   VARCHAR(16) DEFAULT 'MINIO' NOT NULL,
    BUCKET_NAME        VARCHAR(128) NOT NULL,
    OBJECT_NAME        VARCHAR(512) NOT NULL,
    ORIGINAL_FILE_NAME VARCHAR(255) NOT NULL,
    FILE_EXT           VARCHAR(32),
    CONTENT_TYPE       VARCHAR(128),
    FILE_SIZE          BIGINT,
    ETAG               VARCHAR(128),
    UPLOAD_STATUS      VARCHAR(16) DEFAULT 'INIT' NOT NULL,
    UPLOAD_USER_ID     BIGINT,
    UPLOAD_USER_NAME   VARCHAR(64),
    COMPLETED_TIME     TIMESTAMP(6),
    REMARK             VARCHAR(500),
    CREATE_BY          VARCHAR(64),
    CREATE_TIME        TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY          VARCHAR(64),
    UPDATE_TIME        TIMESTAMP(6),

    CONSTRAINT PK_MD_FILE_STORAGE PRIMARY KEY (ID),
    CONSTRAINT IDX_MD_FILE_STORAGE_BIZ UNIQUE (BUSINESS_TYPE, BUSINESS_ID),
    CONSTRAINT UK_MD_FILE_STORAGE_OBJECT UNIQUE (BUCKET_NAME, OBJECT_NAME)
);

CREATE INDEX IDX_MD_FILE_STORAGE_STATUS
    ON MD_FILE_STORAGE (UPLOAD_STATUS);